### ISSUE TITLE
Build failure with vala 0.38.0

### ISSUE THREAD

**Issue by ilovezfs** [radare/valabind#43]
```
make[1]: `config.vala' is up to date.
Compiling config.vala main.vala valabindwriter.vala nodeffiwriter.vala utils.vala girwriter.vala swigwriter.vala cxxwriter.vala ctypeswriter.vala dlangwriter.vala gowriter.vala -> valabind
valac -g --cc="/usr/bin/clang" -X -I/usr/local/opt/gettext/include -X -F/usr/local/Frameworks -X -Os -X -w -X -pipe -X -march=native -X -mmacosx-version-min=10.11 -X -L/usr/local/opt/libffi/lib -X -L/usr/local/opt/gettext/lib -X -L/usr/local/lib -X -F/usr/local/Frameworks -X -Wl,-headerpad_max_install_names -o valabind --pkg posix --pkg libvala-0.38 --save-temps  config.vala main.vala valabindwriter.vala nodeffiwriter.vala utils.vala girwriter.vala swigwriter.vala cxxwriter.vala ctypeswriter.vala dlangwriter.vala gowriter.vala 
swigwriter.vala:25.24-25.38: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.add_includes'
		foreach (string i in CCodeBaseModule.get_ccode_header_filenames (s).split (",")) {
		                     ^^^^^^^^^^^^^^^
swigwriter.vala:197.15-197.29: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.visit_constant'
		var cname = CCodeBaseModule.get_ccode_name (c);
		            ^^^^^^^^^^^^^^^
swigwriter.vala:197.7-197.48: error: var declaration not allowed with non-typed initializer
		var cname = CCodeBaseModule.get_ccode_name (c);
		    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
swigwriter.vala:199.49-199.53: error: The name `cname' does not exist in the context of `SwigWriter.visit_constant'
		extends += "static const char *"+c.name+" = "+cname+";\n";
		                                              ^^^^^
```
etc.

The full build log is here: https://gist.github.com/ilovezfs/7b579a5a0cd0ec3b03557760a9e9a41e

Tested with valabind 0.10.0 and HEAD @ b56c82d3b8acaa4b0942b6248e4c4c15624ba3a1.

```
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
```

**Comment by radare** [comment]
valabind 0.10 is SOOOOO OLD

**Comment by ilovezfs** [comment]
@radare hehe. Note that I also said "and HEAD @ b56c82d."

**Comment by ilovezfs** [comment]
@radare we use 0.10 due to http://radare.org/r/down.html which says that valabind 0.10.0 is the current stable version. Is that information incorrect?

**Comment by radare** [comment]
The webpage is outdated probabky because the release machinery doesnt cares about valabind too much

**Comment by ilovezfs** [comment]
@radare Is the same true for `ired` and `sdb`?

**Comment by radare** [comment]
Probable. We just use github releases now

**Comment by ilovezfs** [comment]
@radare thanks. I wonder how long we would have continued to package the wrong version based on http://radare.org/r/down.html if you and I hadn't stumbled into this conversation. :see_no_evil:

**Comment by radare** [comment]
i have updated the website, but will require more cleanup, feel free to send a pr

**Comment by Gottox** [comment]
Same problem on void.

**Comment by Gottox** [comment]
Problem is that vala fails to install valacodegen.h at 0.38. No idea why this happens.

**Comment by Gottox** [comment]
Build output:
```
~/src/void-packages/srcpkgs/valabind(gnome-3.26 ✗) ../../xbps-src pkg  
=> Using `/work/tox/void-packages/hostdir/binpkgs/gnome-3.26' as local repository.
[*] Updating `https://repo.voidlinux.eu/current/musl/x86_64-musl-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/musl/nonfree/x86_64-musl-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/x86_64-musl-repodata': Not Found
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/nonfree/x86_64-musl-repodata': Not Found
[*] Updating `https://repo.voidlinux.eu/current/aarch64/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/aarch64/x86_64-musl-repodata': Not Found
=> valabind-1.4.0_1: removing autodeps, please wait...
=> valabind-1.4.0_1: building ...
   [host] pkg-config-0.29.2_1: found (https://repo.voidlinux.eu/current/musl)
   [host] vala-devel-0.38.1_1: found (/host/binpkgs/gnome-3.26)
   [target] vala-devel-0.38.1_1: found (/host/binpkgs/gnome-3.26)
   [target] glib-devel-2.54.0_1: found (/host/binpkgs/gnome-3.26)
   [runtime] vala-devel>=0.26: found vala-devel-0.38.1_1 (/host/binpkgs/gnome-3.26)
=> valabind-1.4.0_1: installing host dependency 'pkg-config-0.29.2_1' ...
=> valabind-1.4.0_1: installing host dependency 'vala-devel-0.38.1_1' ...
=> valabind-1.4.0_1: installing target dependency 'vala-devel-0.38.1_1' ...
=> valabind-1.4.0_1: installing target dependency 'glib-devel-2.54.0_1' ...
=> valabind-1.4.0_1: running do-fetch hook: 00-distfiles ...
=> valabind-1.4.0_1: running do-extract hook: 00-distfiles ...
=> valabind-1.4.0_1: extracting distfile(s), please wait...
=> valabind-1.4.0_1: running post-extract hook: 00-patches ...
=> valabind-1.4.0_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> valabind-1.4.0_1: running pre-configure hook: 01-override-config ...
=> valabind-1.4.0_1: running pre-configure hook: 02-script-wrapper ...
=> valabind-1.4.0_1: running pre-build hook: 02-script-wrapper ...
=> valabind-1.4.0_1: running do_build ...
make: git: Command not found
make: git: Command not found
Generating config.vala
mkdir -p build
Generating config.vala -> build/config.vapi
Generating main.vala -> build/main.vapi
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
Generating valabindwriter.vala -> build/valabindwriter.vapi
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
Generating nodeffiwriter.vala -> build/nodeffiwriter.vapi
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
Generating utils.vala -> build/utils.vapi
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
Generating girwriter.vala -> build/girwriter.vapi
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
Generating swigwriter.vala -> build/swigwriter.vapi
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
Generating cxxwriter.vala -> build/cxxwriter.vapi
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
Generating ctypeswriter.vala -> build/ctypeswriter.vapi
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
Generating dlangwriter.vala -> build/dlangwriter.vapi
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
make[1]: git: Command not found
make[1]: git: Command not found
Generating gowriter.vala -> build/gowriter.vapi
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
make[1]: Entering directory '/builddir/valabind-1.4.0'
make[1]: git: Command not found
make[1]: git: Command not found
make[1]: 'config.vala' is up to date.
make[1]: Leaving directory '/builddir/valabind-1.4.0'
Compiling config.vala main.vala valabindwriter.vala nodeffiwriter.vala utils.vala girwriter.vala swigwriter.vala cxxwriter.vala ctypeswriter.vala dlangwriter.vala gowriter.vala -> valabind
valac -g --cc="cc" -X -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1 -X -fstack-protector-strong -X -D_FORTIFY_SOURCE=2 -X -mtune=generic -X -O2 -X -pipe -X -g -X -specs=/void-packages/common/environment/configure/gccspecs/hardened-ld -X -Wl,-z,relro -X -Wl,-z,now -X -Wl,--as-needed -o valabind --pkg posix --pkg libvala-0.38 --save-temps  config.vala main.vala valabindwriter.vala nodeffiwriter.vala utils.vala girwriter.vala swigwriter.vala cxxwriter.vala ctypeswriter.vala dlangwriter.vala gowriter.vala 
swigwriter.vala:25.24-25.38: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.add_includes'
		foreach (string i in CCodeBaseModule.get_ccode_header_filenames (s).split (",")) {
		                     ^^^^^^^^^^^^^^^
swigwriter.vala:197.15-197.29: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.visit_constant'
		var cname = CCodeBaseModule.get_ccode_name (c);
		            ^^^^^^^^^^^^^^^
swigwriter.vala:197.7-197.48: error: var declaration not allowed with non-typed initializer
		var cname = CCodeBaseModule.get_ccode_name (c);
		    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
swigwriter.vala:199.49-199.53: error: The name `cname' does not exist in the context of `SwigWriter.visit_constant'
		extends += "static const char *"+c.name+" = "+cname+";\n";
		                                              ^^^^^
swigwriter.vala:216.18-216.32: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.visit_struct'
		string cname = CCodeBaseModule.get_ccode_name (s);
		               ^^^^^^^^^^^^^^^
swigwriter.vala:316.18-316.32: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.visit_method'
		string cname = CCodeBaseModule.get_ccode_name (m), alias = get_alias (m.name);
		               ^^^^^^^^^^^^^^^
swigwriter.vala:240.18-240.32: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.visit_class'
		string cname = CCodeBaseModule.get_ccode_name (c);
		               ^^^^^^^^^^^^^^^
swigwriter.vala:251.7-251.21: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.visit_class'
		if (CCodeBaseModule.is_reference_counting (c))
		    ^^^^^^^^^^^^^^^
swigwriter.vala:252.14-252.28: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.visit_class'
			freefun = CCodeBaseModule.get_ccode_unref_function (c);
			          ^^^^^^^^^^^^^^^
swigwriter.vala:254.14-254.28: error: The name `CCodeBaseModule' does not exist in the context of `SwigWriter.visit_class'
			freefun = CCodeBaseModule.get_ccode_free_function (c);
			          ^^^^^^^^^^^^^^^
nodeffiwriter.vala:20.24-20.38: error: The name `CCodeBaseModule' does not exist in the context of `NodeFFIWriter.add_includes'
		foreach (string i in CCodeBaseModule.get_ccode_header_filenames (s).split (",")) {
		                     ^^^^^^^^^^^^^^^
nodeffiwriter.vala:157.21-157.35: error: The name `CCodeBaseModule' does not exist in the context of `NodeFFIWriter.visit_enum'
			enum_vals += ","+CCodeBaseModule.get_ccode_name (v);
			                 ^^^^^^^^^^^^^^^
nodeffiwriter.vala:210.7-210.21: error: The name `CCodeBaseModule' does not exist in the context of `NodeFFIWriter.visit_class'
		if (CCodeBaseModule.is_reference_counting (c))
		    ^^^^^^^^^^^^^^^
nodeffiwriter.vala:211.14-211.28: error: The name `CCodeBaseModule' does not exist in the context of `NodeFFIWriter.visit_class'
			freefun = CCodeBaseModule.get_ccode_unref_function (c);
			          ^^^^^^^^^^^^^^^
nodeffiwriter.vala:213.14-213.28: error: The name `CCodeBaseModule' does not exist in the context of `NodeFFIWriter.visit_class'
			freefun = CCodeBaseModule.get_ccode_free_function (c);
			          ^^^^^^^^^^^^^^^
nodeffiwriter.vala:243.18-243.32: error: The name `CCodeBaseModule' does not exist in the context of `NodeFFIWriter.visit_method'
		string cname = CCodeBaseModule.get_ccode_name (m), name = m.name;
		               ^^^^^^^^^^^^^^^
ctypeswriter.vala:145.24-145.38: error: The name `CCodeBaseModule' does not exist in the context of `CtypesWriter.add_includes'
		foreach (string i in CCodeBaseModule.get_ccode_header_filenames (s).split (",")) {
		                     ^^^^^^^^^^^^^^^
ctypeswriter.vala:471.18-471.32: error: The name `CCodeBaseModule' does not exist in the context of `CtypesWriter.visit_method'
		string cname = CCodeBaseModule.get_ccode_name (m);
		               ^^^^^^^^^^^^^^^
ctypeswriter.vala:454.18-454.32: error: The name `CCodeBaseModule' does not exist in the context of `CtypesWriter.visit_delegate'
		string cname = CCodeBaseModule.get_ccode_name (d);
		               ^^^^^^^^^^^^^^^
girwriter.vala:187.15-187.29: error: The name `CCodeBaseModule' does not exist in the context of `GirWriter.walk_constant'
		var cname = CCodeBaseModule.get_ccode_name (f);
		            ^^^^^^^^^^^^^^^
girwriter.vala:187.7-187.48: error: var declaration not allowed with non-typed initializer
		var cname = CCodeBaseModule.get_ccode_name (f);
		    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
girwriter.vala:191.34-191.38: error: The name `cname' does not exist in the context of `GirWriter.walk_constant'
		extends += "<constant name=\""+cname+"\" value=\""+cvalue+"\">\n";
		                               ^^^^^
girwriter.vala:203.23-203.37: error: The name `CCodeBaseModule' does not exist in the context of `GirWriter.process_includes'
		foreach (var foo in CCodeBaseModule.get_ccode_header_filenames (s).split (",")) {
		                    ^^^^^^^^^^^^^^^
girwriter.vala:217.14-217.28: error: The name `CCodeBaseModule' does not exist in the context of `GirWriter.walk_field'
		var name = CCodeBaseModule.get_ccode_name (f);
		           ^^^^^^^^^^^^^^^
girwriter.vala:217.7-217.47: error: var declaration not allowed with non-typed initializer
		var name = CCodeBaseModule.get_ccode_name (f);
		    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
girwriter.vala:220.35-220.38: error: The name `name' does not exist in the context of `GirWriter.walk_field'
		externs += "    <field name=\""+name+"\" allow-none=\"1\">\n";
		                                ^^^^
girwriter.vala:292.18-292.32: error: The name `CCodeBaseModule' does not exist in the context of `GirWriter.walk_method'
		string cname = CCodeBaseModule.get_ccode_name (m);
		               ^^^^^^^^^^^^^^^
girwriter.vala:305.25-305.39: error: The name `CCodeBaseModule' does not exist in the context of `GirWriter.walk_method'
		else ret = get_ctype (CCodeBaseModule.get_ccode_name (m.return_type));
		                      ^^^^^^^^^^^^^^^
girwriter.vala:341.36-341.50: error: The name `CCodeBaseModule' does not exist in the context of `GirWriter.walk_method'
				string? arg_ctype = get_ctype (CCodeBaseModule.get_ccode_name (bar));
				                               ^^^^^^^^^^^^^^^
girwriter.vala:240.16-240.30: error: The name `CCodeBaseModule' does not exist in the context of `GirWriter.walk_class'
		classcname = CCodeBaseModule.get_ccode_name (c);
		             ^^^^^^^^^^^^^^^
dlangwriter.vala:160.23-160.37: error: The name `CCodeBaseModule' does not exist in the context of `DlangWriter.process_includes'
		foreach (var foo in CCodeBaseModule.get_ccode_header_filenames (s).split (",")) {
		                    ^^^^^^^^^^^^^^^
dlangwriter.vala:179.5-179.19: error: The name `CCodeBaseModule' does not exist in the context of `DlangWriter.walk_field'
				CCodeBaseModule.get_ccode_name (f)));
				^^^^^^^^^^^^^^^
dlangwriter.vala:217.20-217.34: error: The name `CCodeBaseModule' does not exist in the context of `DlangWriter.walk_class'
		classcname = "_"+CCodeBaseModule.get_ccode_name (c);
		                 ^^^^^^^^^^^^^^^
dlangwriter.vala:257.8-257.22: error: The name `CCodeBaseModule' does not exist in the context of `DlangWriter.walk_class'
			if (CCodeBaseModule.is_reference_counting (c)) {
			    ^^^^^^^^^^^^^^^
dlangwriter.vala:258.23-258.37: error: The name `CCodeBaseModule' does not exist in the context of `DlangWriter.walk_class'
				string? freefun = CCodeBaseModule.get_ccode_unref_function (c);
				                  ^^^^^^^^^^^^^^^
dlangwriter.vala:262.23-262.37: error: The name `CCodeBaseModule' does not exist in the context of `DlangWriter.walk_class'
				string? freefun = CCodeBaseModule.get_ccode_free_function (c);
				                  ^^^^^^^^^^^^^^^
dlangwriter.vala:297.18-297.32: error: The name `CCodeBaseModule' does not exist in the context of `DlangWriter.walk_method'
		string cname = CCodeBaseModule.get_ccode_name (m);
		               ^^^^^^^^^^^^^^^
dlangwriter.vala:312.45-312.59: error: The name `CCodeBaseModule' does not exist in the context of `DlangWriter.walk_method'
		ret = get_ctype (is_generic (ret)?  ret : CCodeBaseModule.get_ccode_name (m.return_type));
		                                          ^^^^^^^^^^^^^^^
dlangwriter.vala:312.45-312.90: error: var declaration not allowed with non-typed initializer
		ret = get_ctype (is_generic (ret)?  ret : CCodeBaseModule.get_ccode_name (m.return_type));
		                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dlangwriter.vala:335.34-335.48: error: The name `CCodeBaseModule' does not exist in the context of `DlangWriter.walk_method'
			string? arg_type = get_ctype (CCodeBaseModule.get_ccode_name (bar));
			                              ^^^^^^^^^^^^^^^
cxxwriter.vala:150.23-150.37: error: The name `CCodeBaseModule' does not exist in the context of `CxxWriter.process_includes'
		foreach (var foo in CCodeBaseModule.get_ccode_header_filenames (s).split (",")) {
		                    ^^^^^^^^^^^^^^^
cxxwriter.vala:169.5-169.19: error: The name `CCodeBaseModule' does not exist in the context of `CxxWriter.walk_field'
				CCodeBaseModule.get_ccode_name (f)));
				^^^^^^^^^^^^^^^
cxxwriter.vala:183.16-183.30: error: The name `CCodeBaseModule' does not exist in the context of `CxxWriter.walk_class'
		classcname = CCodeBaseModule.get_ccode_name (c);
		             ^^^^^^^^^^^^^^^
cxxwriter.vala:216.8-216.22: error: The name `CCodeBaseModule' does not exist in the context of `CxxWriter.walk_class'
			if (CCodeBaseModule.is_reference_counting (c)) {
			    ^^^^^^^^^^^^^^^
cxxwriter.vala:217.23-217.37: error: The name `CCodeBaseModule' does not exist in the context of `CxxWriter.walk_class'
				string? freefun = CCodeBaseModule.get_ccode_unref_function (c);
				                  ^^^^^^^^^^^^^^^
cxxwriter.vala:221.23-221.37: error: The name `CCodeBaseModule' does not exist in the context of `CxxWriter.walk_class'
				string? freefun = CCodeBaseModule.get_ccode_free_function (c);
				                  ^^^^^^^^^^^^^^^
cxxwriter.vala:256.18-256.32: error: The name `CCodeBaseModule' does not exist in the context of `CxxWriter.walk_method'
		string cname = CCodeBaseModule.get_ccode_name (m);
		               ^^^^^^^^^^^^^^^
cxxwriter.vala:270.45-270.59: error: The name `CCodeBaseModule' does not exist in the context of `CxxWriter.walk_method'
		ret = get_ctype (is_generic (ret)?  ret : CCodeBaseModule.get_ccode_name (m.return_type));
		                                          ^^^^^^^^^^^^^^^
cxxwriter.vala:270.45-270.90: error: var declaration not allowed with non-typed initializer
		ret = get_ctype (is_generic (ret)?  ret : CCodeBaseModule.get_ccode_name (m.return_type));
		                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cxxwriter.vala:287.34-287.48: error: The name `CCodeBaseModule' does not exist in the context of `CxxWriter.walk_method'
			string? arg_type = get_ctype (CCodeBaseModule.get_ccode_name (bar));
			                              ^^^^^^^^^^^^^^^
gowriter.vala:468.23-468.37: error: The name `CCodeBaseModule' does not exist in the context of `GoSrcWriter.process_includes'
		foreach (var foo in CCodeBaseModule.get_ccode_header_filenames (s).split (",")) {
		                    ^^^^^^^^^^^^^^^
gowriter.vala:176.14-176.28: error: The name `CCodeBaseModule' does not exist in the context of `GoNamer.get_field_cname'
		string n = CCodeBaseModule.get_ccode_name(f);
		           ^^^^^^^^^^^^^^^
gowriter.vala:189.10-189.24: error: The name `CCodeBaseModule' does not exist in the context of `GoNamer.get_method_cname'
		return CCodeBaseModule.get_ccode_name(m);
		       ^^^^^^^^^^^^^^^
gowriter.vala:256.10-256.24: error: The name `CCodeBaseModule' does not exist in the context of `GoNamer.get_class_cname'
		return CCodeBaseModule.get_ccode_name(c);
		       ^^^^^^^^^^^^^^^
gowriter.vala:264.10-264.24: error: The name `CCodeBaseModule' does not exist in the context of `GoNamer.get_struct_cname'
		return CCodeBaseModule.get_ccode_name(s);
		       ^^^^^^^^^^^^^^^
gowriter.vala:568.13-568.27: error: The name `CCodeBaseModule' does not exist in the context of `GoSrcWriter.walk_enum'
		var pfx = CCodeBaseModule.get_ccode_prefix(e);
		          ^^^^^^^^^^^^^^^
gowriter.vala:568.7-568.47: error: var declaration not allowed with non-typed initializer
		var pfx = CCodeBaseModule.get_ccode_prefix(e);
		    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gowriter.vala:569.47-569.49: error: The name `pfx' does not exist in the context of `GoSrcWriter.walk_enum'
		debug("walk_enum(pfx: %s, name: %s)".printf(pfx, e.name));
		                                            ^^^
gowriter.vala:575.40-575.42: error: The name `pfx' does not exist in the context of `GoSrcWriter.walk_enum'
			ret += "    %s%s = C.%s%s\n".printf(pfx, namer.get_enum_value_name(v), pfx, namer.get_enum_value_cname(v));
			                                    ^^^
gowriter.vala:575.75-575.77: error: The name `pfx' does not exist in the context of `GoSrcWriter.walk_enum'
			ret += "    %s%s = C.%s%s\n".printf(pfx, namer.get_enum_value_name(v), pfx, namer.get_enum_value_cname(v));
			                                                                       ^^^
gowriter.vala:825.9-825.23: error: The name `CCodeBaseModule' does not exist in the context of `GoSrcWriter.get_class_src'
				if (CCodeBaseModule.is_reference_counting (c)) {
				    ^^^^^^^^^^^^^^^
gowriter.vala:826.24-826.38: error: The name `CCodeBaseModule' does not exist in the context of `GoSrcWriter.get_class_src'
					string? freefun = CCodeBaseModule.get_ccode_unref_function (c);
					                  ^^^^^^^^^^^^^^^
gowriter.vala:834.24-834.38: error: The name `CCodeBaseModule' does not exist in the context of `GoSrcWriter.get_class_src'
					string? freefun = CCodeBaseModule.get_ccode_free_function (c);
					                  ^^^^^^^^^^^^^^^
Compilation failed: 63 error(s), 0 warning(s)
make: *** [Makefile:62: valabind] Error 1
=> ERROR: valabind-1.4.0_1: failed to run do_build() at line 9.
```

**Comment by anthraxx** [comment]
same on Arch Linux :crying_cat_face: any progress?

**Comment by trufae** [comment]
CCodeBaseModule is internal in Vala 0.38, so there's no way to make valabind work on vala 0.38 unless the vala developers decide to make that private api public again or at least in a separate library.

Meanwhile i would recommend you to use the r2pm package which ships the 0.36.4

**Comment by trufae** [comment]
Can you please fill an issue in https://bugzilla.gnome.org/enter_bug.cgi ?

**Comment by anthraxx** [comment]
@ilovezfs did you have a chance to report this at gnome? Would be nice :cat:

**Comment by radare** [comment]
Its already reported. They are working on a fix to bring back those internal apis. Probably the next release of vala will be good for valabind

**Comment by anthraxx** [comment]
@radare thats awesome! thanks for the feedback :tada:

**Comment by deft01** [comment]
Same issue for all of these versions : 
0.8.0
0.9.0
0.9.2
1.2.0
1.3.0
1.4.0

I'm compiling on xubuntu.

**Comment by jbicha** [comment]
> Its already reported.

@radare Can you point to bug numbers?

> They are working on a fix to bring back those internal apis.

Are you sure about that?

**Comment by radare** [comment]
Yes

**Comment by jbicha** [comment]
https://bugzilla.gnome.org/788837

**Comment by radare** [comment]
getting closer to support new vala in master

**Comment by radare** [comment]
Fixed in master!!!
